In [1]:
def my_function():
    pass

In [2]:
def my_sq(x):
    return x ** 2

In [3]:
my_sq(4)

16

In [4]:
def avg_2(x, y):
    return (x + y) / 2

In [5]:
avg_2(10, 20)

15.0

In [6]:
assert avg_2(10, 20) == 15.0

In [7]:
import pandas as pd

In [8]:
df=pd.DataFrame({'a':[10,20,30],
                 'b':[20,30,40]})
df

a   b
0  10  20
1  20  30
2  30  40

In [9]:
# If all we need to do is apply a rudimentary arithmetic operation,
# there is no need to use apply.
df['a'] ** 2

0    100
1    400
2    900
Name: a, dtype: int64

In [10]:
type(df['a'])

pandas.core.series.Series

In [11]:
def my_sq(x):
    # assert isinstance(x, int)
    return x ** 2

In [12]:
df['a'].apply(my_sq)

0    100
1    400
2    900
Name: a, dtype: int64

In [13]:
def my_exp(x, e):
    return x ** e

In [14]:
my_exp(2, 2)

4

In [15]:
my_exp(2, 10)

1024

In [16]:
df['a'].apply(my_exp, e=10)

0        10000000000
1     10240000000000
2    590490000000000
Name: a, dtype: int64

In [17]:
def print_me(x):
    print(x)

In [18]:
df

a   b
0  10  20
1  20  30
2  30  40

In [19]:
df.apply(print_me, axis=0)

0    10
1    20
2    30
Name: a, dtype: int64
0    20
1    30
2    40
Name: b, dtype: int64


a    None
b    None
dtype: object

In [20]:
def avg_3(x, y, z):
    return (x + y + z) / 3

In [21]:
df.apply(avg_3)

TypeError: ("avg_3() missing 2 required positional arguments: 'y' and 'z'", 'occurred at index a')

In [22]:
def avg_3_apply(col):
    x = col[0]
    y = col[1]
    z = col[2]
    return (x + y + z) / 3

In [23]:
df.apply(avg_3_apply)

a    20.0
b    30.0
dtype: float64

In [24]:
import numpy as np

In [25]:
df.apply(np.mean)

a    20.0
b    30.0
dtype: float64

In [26]:
df.apply(avg_3_apply, axis=1)

IndexError: ('index out of bounds', 'occurred at index 0')

In [28]:
df

a   b
0  10  20
1  20  30
2  30  40

In [29]:
def avg_2_apply(row):
    x = row[0]
    y = row[1]
    return (x + y) / 2

In [30]:
df.apply(avg_2_apply, axis=1)

0    15.0
1    25.0
2    35.0
dtype: float64

In [31]:
import seaborn as sns

In [32]:
titanic = sns.load_dataset('titanic')

In [33]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [34]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
survived       891 non-null int64
pclass         891 non-null int64
sex            891 non-null object
age            714 non-null float64
sibsp          891 non-null int64
parch          891 non-null int64
fare           891 non-null float64
embarked       889 non-null object
class          891 non-null category
who            891 non-null object
adult_male     891 non-null bool
deck           203 non-null category
embark_town    889 non-null object
alive          891 non-null object
alone          891 non-null bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.6+ KB


In [35]:
def count_missing(vec):
    """Counts the number of missing values in a vector
    """
    null_vec = pd.isnull(vec)
    null_count = np.sum(null_vec)
    return null_count

In [36]:
count_missing?

Signature: count_missing(vec)
Docstring:
Counts the number of missing values in a vector
    
File:      h:\edanda\pythonprojects\educational\pandas_for_everyone\training\<ipython-input-35-8afc8d0851c0>
Type:      function


In [37]:
cmis_col = titanic.apply(count_missing)

In [38]:
cmis_col

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [39]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
survived       891 non-null int64
pclass         891 non-null int64
sex            891 non-null object
age            714 non-null float64
sibsp          891 non-null int64
parch          891 non-null int64
fare           891 non-null float64
embarked       889 non-null object
class          891 non-null category
who            891 non-null object
adult_male     891 non-null bool
deck           203 non-null category
embark_town    889 non-null object
alive          891 non-null object
alone          891 non-null bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.6+ KB


In [40]:
cmis_row = titanic.apply(count_missing, axis=1)

In [41]:
cmis_row

0      1
1      0
2      1
3      0
4      1
      ..
886    1
887    0
888    2
889    0
890    1
Length: 891, dtype: int64

In [42]:
def avg_2(x, y):
    return (x + y) / 2

In [43]:
df

a   b
0  10  20
1  20  30
2  30  40

In [44]:
avg_2(df['a'], df['b'])

0    15.0
1    25.0
2    35.0
dtype: float64

In [45]:
(df['a'] + df['b']) / 2

0    15.0
1    25.0
2    35.0
dtype: float64

In [46]:
def avg_2_mod(x, y):
    if (x == 20):
        return np.NaN
    else:
        return (x + y) / 2

In [47]:
avg_2_mod(df['a'], df['b'])

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [48]:
avg_2_mod(10, 20)

15.0

In [49]:
avg_2_mod(20, 30)

nan

In [50]:
import numpy as np

In [51]:
avg_2_mod_vec = np.vectorize(avg_2_mod)

In [52]:
df

a   b
0  10  20
1  20  30
2  30  40

In [53]:
avg_2_mod_vec(df['a'], df['b'])

array([15., nan, 35.])

In [54]:
@np.vectorize
def v_avg_2_mod(x, y):
    if (x == 20):
        return np.NaN
    else:
        return (x + y) / 2

In [55]:
v_avg_2_mod(df['a'], df['b'])

array([15., nan, 35.])

In [57]:
import numba

In [58]:
@numba.vectorize
def v_avg_2_mod_numba(x, y):
    if (x == 20):
        return np.NaN
    else:
        return (x + y) / 2

In [59]:
v_avg_2_mod_numba(df['a'].values, df['b'].values)

array([15., nan, 35.])

In [60]:
%%timeit
avg_2(df['a'], df['b'])

834 µs ± 393 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [61]:
%%timeit
v_avg_2_mod(df['a'], df['b'])

571 µs ± 229 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [62]:
%%timeit
v_avg_2_mod_numba(df['a'].values, df['b'].values)

38.8 µs ± 14.7 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
